
DL = ../../../../Downloads

# Download all current DNA items for Homo sapiens
NCBI_Gene_hsa_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_All_Homo_sapiens.tsv

# Download all protein-coding genes for Home sapiens
NCBI_Gene_hsa_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_ProteinCoding.tsv

# Download all microRNA for Home sapiens
NCBI_Gene_hsa_uRNA:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_microRNA.tsv


# Download all current DNA items for Mus musculus (house mouse)
NCBI_Gene_mus_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_All_mus.tsv

# Download all protein-coding genes for Mus musculus (house mouse)
NCBI_Gene_mus_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_PC_mus.tsv

# Download all microRNA for Mus musculus (house mouse)
NCBI_Gene_mus_uRNA:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_microRNA_mus.tsv

