
DL = ../../../../Downloads

rpt:
	wc -l NCBI/genes_NCBI_*.tsv
	grep ":" makefile


# Download all current DNA items for Homo sapiens
NCBI_Gene_hsa_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_hsa_All.tsv

# Download all protein-coding genes for Home sapiens
NCBI_Gene_hsa_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_hsa_ProteinCoding.tsv

# Download all microRNA for Home sapiens
NCBI_Gene_hsa_uRNA:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_hsa_microRNA.tsv



# Download all current DNA items for Mus musculus (house mouse)
NCBI_Gene_mmu_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_mmu_All.tsv

# Download all protein-coding genes for Mus musculus (house mouse)
NCBI_Gene_mmu_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_mmu_ProteinCoding.tsv

# Download all microRNA for Mus musculus (house mouse)
NCBI_Gene_mmu_uRNA:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_mmu_microRNA.tsv



# Download all current DNA items for Drosophila melanogaster (fruit fly)
NCBI_Gene_dme_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_dme_All.tsv

# Download all protein-coding genes for Drosophila melanogaster (fruit fly)
NCBI_Gene_dme_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_dme_ProteinCoding.tsv

# Download all noncoding items for Drosophila melanogaster (fruit fly)
NCBI_Gene_dme_noncoding:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_dme_noncoding.tsv



# Download all current DNA items for Arabidopsis thaliana (thale cress)
NCBI_Gene_ath_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_ath_All.tsv

# Download all protein-coding genes for Arabidopsis thaliana (thale cress)
NCBI_Gene_ath_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_ath_ProteinCoding.tsv

# Download all noncoding items for Arabidopsis thaliana (thale cress)
NCBI_Gene_ath_noncoding:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_ath_noncoding.tsv



# Download SNPs
NCBI_dbSNP_hsa_OMIM:
	mv $(DL)/snp_result.txt ./NCBI/dbSNP_NCBI_hsa_OMIM.tsv
