
DL = ../../../../Downloads

# Download all current DNA items for Homo sapiens
NCBI_Gene_hsa_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_hsa_All.tsv

# Download all protein-coding genes for Home sapiens
NCBI_Gene_hsa_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_hsa_ProteinCoding.tsv

# Download all microRNA for Home sapiens
NCBI_Gene_hsa_uRNA:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_hsa_microRNA.tsv



# Download all current DNA items for Mus musculus (house mouse)
NCBI_Gene_mus_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_mus_All.tsv

# Download all protein-coding genes for Mus musculus (house mouse)
NCBI_Gene_mus_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_mus_ProteinCoding.tsv

# Download all microRNA for Mus musculus (house mouse)
NCBI_Gene_mus_uRNA:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_mus_microRNA.tsv



# Download all current DNA items for Drosophila melanogaster (fruit fly)
NCBI_Gene_dme_all:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_dme_All.tsv

# Download all protein-coding genes for Drosophila melanogaster (fruit fly)
NCBI_Gene_dme_pc:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_dme_ProteinCoding.tsv

# Download all microRNA for Drosophila melanogaster (fruit fly)
NCBI_Gene_dme_uRNA:
	mv $(DL)/gene_result.txt ./NCBI/genes_NCBI_dme_microRNA.tsv
